### ISSUE TITLE
Rendering HTML

### ISSUE THREAD

**Issue by wSedlacek** [ChimeHQ/Neon#37]
I am interested in using a project like this that uses treesitter for a Vapor web application.
I am still pretty new to the world of Swift but I was trying to reason about if the APIs provided in this library could be used to render HTML (and if this can even run on the server)

I would love some thoughts on what HTML rendering might look like and if it would use Neon or the lower level SwiftTreeSitter

**Comment by mattmassicotte** [comment]
First, I'm really happy you asked!

Because of the context here, when you say "rendering HTML" I'm going to assume you mean "performing highlighting on html text" and not "turning that HTML into a web page like a browser does". Is that right?

SwiftTreeSitter can definitely do this. However, that's a pretty low-level library and the work required to support efficient incremental and lazy processing and invalidation is non-trivial. Does your application need that? It may not, unless you have some kind of server-side editor functionality. I'd really need to understand better what you would like to do.

I also want to add that *today* Neon is pretty poor fit for Linux because so much of it is designed to work with Apple's systems. Its `TreeSittterClient` type probably does work, but many other components will not. But, I'm actually actively working on taking the core support for incremental, lazy processing/invalidation out of `TreeSittterClient` and `Highlighter` in an effort to make Neon more general-purpose. And I'm actually quite close!

**Comment by wSedlacek** [comment]
> Because of the context here, when you say "rendering HTML" I'm going to assume you mean "performing highlighting on html text" and not "turning that HTML into a web page like a browser does". Is that right?

Yeah! I want to do server side Syntax Highlighting for a blog.

> SwiftTreeSitter can definitely do this. However, that's a pretty low-level library and the work required to support efficient incremental and lazy processing and invalidation is non-trivial. Does your application need that? It may not, unless you have some kind of server-side editor functionality. I'd really need to understand better what you would like to do.

Really I just need to add the highlights once. This could be done either when a blog post is created or when it is requested (depending on how long the parsing takes would determine when it would be best to do this work)

> I also want to add that today Neon is pretty poor fit for Linux because so much of it is designed to work with Apple's systems. Its TreeSittterClient type probably does work, but many other components will not.

I haven’t tried to run it on linux just yet, but I do have this proof of concept working in a swift CLI application.


```swift
  let source = """
    func hello() {
        print("hello from tree-sitter")
    }
    """

  let swiftHighlightsQueryUrl = URL(filePath: app.directory.resourcesDirectory)
    .appending(path: "Highlights")
    .appending(path: "swift.scm")

  let swiftLanguage = Language(language: tree_sitter_swift())
  let swiftHighlightsQuery = try swiftLanguage.query(contentsOf: swiftHighlightsQueryUrl)

  let parser = Parser()
  try parser.setLanguage(swiftLanguage)

  let tree = parser.parse(source)!

  let cursor = swiftHighlightsQuery.execute(node: tree.rootNode!)
  for match in cursor {
    for capture in match.captures {
      print("type \(capture.highlight?.name)")
      print("range \(capture.node.range) ")
    }
  }
```

It outputs
```
type Optional("keyword.function")
range {0, 4} 
type Optional("method")
range {5, 5} 
type Optional("punctuation.bracket")
range {10, 1} 
type Optional("punctuation.bracket")
range {11, 1} 
type Optional("punctuation.bracket")
range {13, 1} 
type Optional("function.call")
range {19, 5} 
type Optional("punctuation.bracket")
range {24, 1} 
type Optional("string")
range {25, 1} 
type Optional("string")
range {26, 22} 
type Optional("string")
range {48, 1} 
type Optional("punctuation.bracket")
range {49, 1} 
type Optional("punctuation.bracket")
range {51, 1} 
```

I am thinking from here we just insert `<span>` with `class` as the type around each of the ranges (working from the end of the string to the front to preseve the indexes as they are added)

And then a simple stylesheet can be made with any of the classes and we are done.

**Comment by mattmassicotte** [comment]
Ok! Neon is really about managing document changes efficiently. I'm working on updating the documentation to make this clear along with the other stuff I mentioned.

I think you can get by with SwiftTreeSitter directly. A few things I want to point out though since I have you!

- SwiftTreeSitter's `Language` type has a facility for looking up bundle resources like queries. Worth checking out!
- SwiftTreeSitter's `QueryCursor` and `ResolvingQueryCursor` have a`highlights()` method that does match interpretation for you along with a few other things.
- Paying close attention to the highlight.scm files you find. People rarely commit needed fixes back to the parser repos. I try to when I can, but they are often broken in strange ways.

(I have made notes of all of this and will update the SwiftTreeSitter documentation to make it clearer as well).

Also, you'll still have to deal with applying themes manually. If you have interest in collaborating here, I'm very up for it. I started a placeholder repo for this exact kind of work, but I have been a little side-tracked lately. https://github.com/ChimeHQ/ThemePark

Happy highlighting!
