### ISSUE TITLE
Text highlighting after edit does not work

### ISSUE THREAD

**Issue by Wouter01** [ChimeHQ/Neon#41]
When adding new text, it is not styled. It will still get styled if the scrollview is resized. It looks like commit 45d3d62 is the last with working styling after typing. This issue also occurs in the demo project

**Comment by mattmassicotte** [comment]
Here's what happened. Previously, the various components were automatically validating any invalid visible regions after a change. This does work, but has timing issues. I changed things to make validation an explicit operation. If you want to synchronously apply styling on a change, it must happen after the layout has been updated.

With TextKit 1, that's not possible (as far as I know) without making a custom NSTextStorage subclass.
With TextKit 2, the layout process itself is asynchronous. I don't believe their are any hooks to know when the system has completed a particular section of layout.

You can also just do the styling on the next runloop turn. This is very easy, but can result in a flicker where text was rendered without styling and then immediately gets styled after. This is what I've done to fix `TextViewHighlighter` with 33476191bfaf6750c1de8061ebd7ba0bfd89d09c. Because TK2 is fully async, it could be this technique will not always work...
